sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t georgiosktistakis/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true georgiosktistakis/complex-test npm run test

after_success:
  - docker build -t georgiosktistakis/complex-client ./client
  - docker build -t georgiosktistakis/complex-nginx ./nginx
  - docker build -t georgiosktistakis/complex-server ./server
  - docker build -t georgiosktistakis/complex-worker ./worker
  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push georgiosktistakis/complex-client
  - docker push georgiosktistakis/complex-nginx
  - docker push georgiosktistakis/complex-server
  - docker push georgiosktistakis/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "ktistak-complex-app"
  env: "Ktistak-complex-app-env"
  bucket_name: "elasticbeanstalk-eu-north-1-546455860366"
  bucket_path: "ktistak-complex-app" 
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: $AWS_SECRET_KEY